apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment
  labels:
    app: pet-clinic
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
    spec:
      containers:
        - name: pet-clinic
          image: tyitzhak/pet-clinic:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-web-svc
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
